version: '3'

services:
  
  devops-web-test:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
    - "8993:80"
    networks:
    - devops-web-test

  devops-app-test:
    image: nexus-local.tntformacion.com:10000/devops/airports-app:0.8.0
    environment:
      DATABASE_HOST: 'devops-db-test'
      DATABASE_PORT: '3306'
      DATABASE_NAME: 'devops'
      DATABASE_USER: 'devops'
      DATABASE_PASS: ${DATABASE_PASS}
    links:
    - devops-db-test
    depends_on:
    - devops-db-test
    ports:
    - "8080:8080"
    networks:
    - devops-web-test

  devops-db-test:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'devops'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
    - devops-web-test
  
volumes:
  db_data:

networks:
  devops-web-test: